openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/templates/:
    get:
      operationId: listTemplates
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Template'
          description: ''
      tags:
      - api
    post:
      operationId: createTemplate
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Template'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Template'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
          description: ''
      tags:
      - api
  /api/templates/{id}/:
    get:
      operationId: retrieveTemplate
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this plantilla.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
          description: ''
      tags:
      - api
    put:
      operationId: updateTemplate
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this plantilla.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Template'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Template'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateTemplate
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this plantilla.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Template'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Template'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyTemplate
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this plantilla.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Template:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        template:
          type: string
          format: binary
        pub_date:
          type: string
          format: date
          readOnly: true
        context:
          type: string
          nullable: true
          maxLength: 1000
      required:
      - name
      - template
