# Generated by Django 3.1.1 on 2021-05-01 21:31

import album.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('template', models.ImageField(upload_to='templates/', verbose_name='Plantilla')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('context', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Contexto')),
            ],
            options={
                'verbose_name': 'plantilla',
                'verbose_name_plural': 'plantillas',
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme', models.ImageField(upload_to=album.models.Meme.image_dir, verbose_name='Meme')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'meme',
                'verbose_name_plural': 'memes',
            },
        ),
    ]
